### ISSUE TITLE
Crash on Android 10 when proxy is setup on VPN connection.

### ISSUE THREAD

**Issue by vinaykothiyal** [launchdarkly/android-client-sdk#102]
**Is this a support request?** -> **NO**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
Our app is crashing with IllegalArgumentException in the okhttp call with message port out of range -1. This is blocking our release for the supporting proxy on Android 10 devices.

Ours is an enterprise VPN app (Citrix SSO). We are using LD for some time now. When setting up VPN connection, we add proxy (via a PAC file URL) to the VPN interface on device. After that as soon as our app is put in background, above mentioned exception happens and app crashes. It happens almost consistently (8 out of 10 times). By the way our app starts a foreground service for the VPN session, so app has foreground priority at the time of crash.

Any help in addressing the crash is appreciated.

**To reproduce**
Steps to reproduce the behavior.
This happens almost every time when VPN gets activated on Android 10 which has PROXY setup with PAC file URL. Ours is an enterprise VPN (Citrix SSO) app. We use LD for controlling some features. I am not sure if our scenario can be directly reproduced on your end. In any case, here are the steps to reproduce it reliably. 
- Connect to a VPN server which has Proxy configured with PAC file URL on Android 10 device
- Put the app (Citrix SSO) using LD in background by tapping recent apps soft button
- Crash is observed immediately

**Expected behavior**
App should not crash when LD is running in the background.

**Logs**
If applicable, add any log output related to your problem.
`    --------- beginning of crash
2020-06-01 13:21:05.732 26334-26520/com.citrix.CitrixVPN E/AndroidRuntime: FATAL EXCEPTION: okhttp-eventsource-stream-[]-0
    Process: com.citrix.CitrixVPN, PID: 26334
    java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
        at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
        at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
        at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
        at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:129)
        at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:63)
        at okhttp3.internal.connection.StreamAllocation.<init>(StreamAllocation.java:101)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at com.launchdarkly.eventsource.EventSource.connect(EventSource.java:189)
        at com.launchdarkly.eventsource.EventSource.access$1100(EventSource.java:43)
        at com.launchdarkly.eventsource.EventSource$2.run(EventSource.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**SDK version**
Android LD SDK version 2.12.0 (earlier we were using 2.9.0)

**Language version, developer tools**
Java, Android Studio 3.6.3

**OS/platform**
Citrix SSO running on Android Emulator with Android 10. 

**Additional context**

**Comment by gwhelanLD** [comment]
Hi @vinaykothiyal,

Thanks for the detailed issue report. We will attempt to replicate the crash and update this issue when we know more.

Thanks,
@gwhelanLD

**Comment by vinaykothiyal** [comment]
@gwhelanLD, any updates on this?

**Comment by MichalDanielDobrzanski** [comment]
Should be closed I guess, since it was part of [3.1.1](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.1.1)

**Comment by eli-darkly** [comment]
We do believe this was addressed in 3.1.1, so I'm closing this but please feel free to reopen if you've seen a similar problem recently.
