### ISSUE TITLE
Crashes on library 2.12.0 on Android 6

### ISSUE THREAD

**Issue by yzheng988** [launchdarkly/android-client-sdk#105]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
We saw some crashes on Crashlytics (62 crashes affecting 4 users) on `SharedPrefsSummaryEventStore.java line 100`. It only occurs on Android 6

**To reproduce**
Unable to, crash occur on end user

**Expected behavior**

**Logs**
Stack Trace:
```
Fatal Exception: java.lang.IllegalStateException: Not a JSON Object: null
       at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
       at com.launchdarkly.android.SharedPrefsSummaryEventStore.getSummaryEventNoSync(SharedPrefsSummaryEventStore.java:100)
       at com.launchdarkly.android.SharedPrefsSummaryEventStore.getSummaryEventAndClear(SharedPrefsSummaryEventStore.java:114)
       at com.launchdarkly.android.DefaultEventProcessor$Consumer.flush(DefaultEventProcessor.java:126)
       at com.launchdarkly.android.DefaultEventProcessor$Consumer.run(DefaultEventProcessor.java:116)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

```
**SDK version**
2.12.0

**Language version, developer tools**
Kotlin 1.3.72

**OS/platform**
Android 6

**Additional context**

**Comment by gwhelanLD** [comment]
Hi @yzheng988,

Thanks for reporting this issue. I can see how this exception could be thrown if the device storage got into a particular bad state, but I'm not sure how that would have happened. Regardless, I've made some changes to improve the resiliency of the logic to allow the SDK to recover from that state. We'll have a patch release out soon with those changes.

Thanks,
@gwhelanLD

**Comment by yzheng988** [comment]
Thanks @gwhelanLD for your response and efforts.

**Comment by gwhelanLD** [comment]
Thanks for your patience with this issue. It should be resolved in the https://github.com/launchdarkly/android-client-sdk/releases/tag/2.14.0. Feel free to reopen if this release does not resolved the errors.

Thanks again for the report,
@gwhelanLD
