### ISSUE TITLE
Crash in com.launchdarkly.android.PollingUpdater.startPolling

### ISSUE THREAD

**Issue by weizheng-nathan** [launchdarkly/android-client-sdk#115]
java.lang.IllegalStateException: 
  at android.os.Parcel.createException (Parcel.java:2096)
  at android.os.Parcel.readException (Parcel.java:2056)
  at android.os.Parcel.readException (Parcel.java:2004)
  at android.app.IAlarmManager$Stub$Proxy.set (IAlarmManager.java:338)
  at android.app.AlarmManager.setImpl (AlarmManager.java:730)
  at android.app.AlarmManager.setInexactRepeating (AlarmManager.java:831)
  at com.launchdarkly.android.PollingUpdater.startPolling (PollingUpdater.java:40)
  at com.launchdarkly.android.ConnectivityManager.startPolling (ConnectivityManager.java:177)
  at com.launchdarkly.android.ConnectivityManager.attemptTransition (ConnectivityManager.java:257)
  at com.launchdarkly.android.ConnectivityManager.access$300 (ConnectivityManager.java:16)
  at com.launchdarkly.android.ConnectivityManager$1.run (ConnectivityManager.java:63)
  at com.launchdarkly.android.Throttler$1.run (Throttler.java:44)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.os.HandlerThread.run (HandlerThread.java:67)
Caused by: android.os.RemoteException: 
  at com.android.server.AlarmManagerService.setImpl (AlarmManagerService.java:2036)
  at com.android.server.AlarmManagerService$3.set (AlarmManagerService.java:2444)
  at android.app.IAlarmManager$Stub.onTransact (IAlarmManager.java:186)
  at android.os.Binder.execTransactInternal (Binder.java:1056)
  at android.os.Binder.execTransact (Binder.java:1029)

**Comment by weizheng-nathan** [comment]
java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a489, callingPackage: com.glip.mobile
at android.os.Parcel.createException(Parcel.java:2096)
at android.os.Parcel.readException(Parcel.java:2056)
at android.os.Parcel.readException(Parcel.java:2004)
at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:338)
at android.app.AlarmManager.setImpl(AlarmManager.java:730)
at android.app.AlarmManager.setInexactRepeating(AlarmManager.java:831)
at com.launchdarkly.android.PollingUpdater.startPolling(PollingUpdater.java:40)
at com.launchdarkly.android.ConnectivityManager.startPolling(ConnectivityManager.java:177)
at com.launchdarkly.android.ConnectivityManager.attemptTransition(ConnectivityManager.java:257)
at com.launchdarkly.android.ConnectivityManager.access$300(ConnectivityManager.java:16)
at com.launchdarkly.android.ConnectivityManager$1.run(ConnectivityManager.java:63)
at com.launchdarkly.android.Throttler$1.run(Throttler.java:44)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:1995)
at com.android.server.AlarmManagerService$3.set(AlarmManagerService.java:2390)
at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:186)
at android.os.Binder.execTransactInternal(Binder.java:1021)
at android.os.Binder.execTransact(Binder.java:994)

**Comment by gwhelanLD** [comment]
Hi @weizheng-nathan,

Could you please provide more contextual information for this issue? It's hard to determine the cause without more details. However, the second stack trace does look similar to https://github.com/launchdarkly/android-client-sdk/issues/83, are you perhaps using a SDK version before `2.9.1` and could try updating the SDK as a potential solution?

Thanks,
@gwhelanLD

**Comment by weizheng-nathan** [comment]
Hi, @gwhelanLD 
The crash is quite obvious, if the app, which is using LD, created 500 alarms, then LD tried to create one more alarm, the app will crash, because "Maximum limit of concurrent alarms 500 reached"

And the SDK version of LD is 2.12.0

**Comment by bwoskow-ld** [comment]
Hi @weizheng-nathan ,

I see that you're actively discussing this issue with LaunchDarkly's support team on our internal support desk. I'm going to close out this GitHub issue as it isn't efficient to discuss the issue in multiple places.

In the future, you don't need to create issues in both places -- just whichever you think is more appropriate depending on the kind of issue or question you have.

Cheers,
@bwoskow-ld

**Comment by bwoskow-ld** [comment]
This uncaught exception is now caught as of [2.14.1](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.14.1).
