### ISSUE TITLE
Crash on Android Dns.kt line 49 okhttp3.Dns$Companion$DnsSystem.lookup

### ISSUE THREAD

**Issue by Daniel-Glucksman** [launchdarkly/android-client-sdk#125]
Our Firebase crashlytics service reported a crash from the Launch Darkly SDK, which I am posting here:

Non-fatal Exception: java.net.UnknownHostException: Unable to resolve host "mobile.launchdarkly.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
       at java.net.InetAddress.getAllByName(InetAddress.java:787)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.launchdarkly.android.SSLHandshakeInterceptor.intercept(TLSUtils.java:72)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
       at com.launchdarkly.android.DiagnosticEventProcessor.sendDiagnosticEventSync(DiagnosticEventProcessor.java:116)
       at com.launchdarkly.android.DiagnosticEventProcessor$4.run(DiagnosticEventProcessor.java:99)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)

Logs attached from device
[com.grocerkey.pickerapp.staging_issue_16086cfe06c8a0080ccc5b4ba7229471_error_session_608FCD5E02F200013E0DF0F75F9CA2F7_DNE_0_v2.log](https://github.com/launchdarkly/android-client-sdk/files/6426451/com.grocerkey.pickerapp.staging_issue_16086cfe06c8a0080ccc5b4ba7229471_error_session_608FCD5E02F200013E0DF0F75F9CA2F7_DNE_0_v2.log)

![image](https://user-images.githubusercontent.com/1812255/117128880-a76c4880-ada6-11eb-9c1f-a74c9ef12e29.png)

**Comment by bwoskow-ld** [comment]
Hi @Daniel-Glucksman,

Thanks for reporting. This error is currently prone to happen when the Android SDK attempts to send this event on a device without a network connection. This was previously reported as #107. To keep our issue tracker clear of duplicates I'm going to close this and ask that you follow that ticket for updates.

We've already fixed the issue on our private mirror and will include it in the next Android release. Watch #107 for updates.

Cheers,
@bwoskow-ld
