### ISSUE TITLE
Excessive DNS lookout errors logged

### ISSUE THREAD

**Issue by VyshasDojo** [launchdarkly/android-client-sdk#169]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
Errors are logged when app starts without network connections. The fix noted in https://github.com/launchdarkly/android-client-sdk/issues/107 is still not fixed in 3.1.1

**Expected behavior**
ensure the logs are not spammed.

**Logs**
`Caused by java.net.UnknownHostException: Unable to resolve host "clientsdk.launchdarkly.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.java:5)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:32)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:32)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:32)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:12)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:12)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:12)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:7)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:127)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:7)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:21)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:7)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:26)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:7)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:12)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:8)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**SDK version**
3.1.1

**Language version, developer tools**
Kotlin , Android.
**OS/platform**
Android
**Additional context**

**Comment by louis-launchdarkly** [comment]
Hello @VyshasDojo, thank you for the report. We will continue the investigation of this issue as you noted v3.1.1. didn't seem to fix it.

_Filed Internally as 155373_

**Comment by louis-launchdarkly** [comment]
Hello @VyshasDojo, sorry for the lack of update as the team was busy preparing the Android SDK major release 4.0.0. In 4.0.0, LaunchDarkly has reworked how the SDK handles connections. If you don't mind, can you upgrade your SDK to 4.0.0 to verify this? For the upgrade path, we recommend upgrading to 3.3.0 first, and if you are not in the Context EAP, upgrade to 4.0.0 to use a single Context with the `user` kind, which will work with all your existing flag rules you have in LaunchDarkly.

**Comment by richardleggett** [comment]
Just to add, the out of the box configuration plants a `Timber.DebugTree` which for network related errors calls Android's `Log.wtf()`, which calls `RuntimeInit.wtf()` (due to `Log.ASSERT` level).

This is being caught and reported by crash reporters such as Sentry. Generating millions of issues in Sentry when devices or LaunchDarkly servers have network issues, e.g.:
- `Exception when fetching flags - java.net.SocketTimeoutException: timeout`
- `Error when attempting to get flag data: [eyTOKENHERE...`
- `Encountered EventStream error connecting to URI: https://clientstream.launchdarkly.com/meval/eyJr...`

Using 4.2.0.
